name: MineBase
author: lifeworldb
version: ${project.version}-${maven.build.timestamp}
main: main.java.Main
description: MineBase es un plugin de alamacenamiento de datos usando como servicio a Firebase de google. Dando una covertura y almacenaje rapido y efectivo